spring.application.name=book-manager

# 1. H2 Console Settings
spring.h2.console.enabled=true

# (Optional) Customize the path, default is /h2-console
spring.h2.console.path=/h2-console

# 2. Database Connection (JDBC) Settings
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=always 

