spring.application.name=book-manager

# 1. H2 Console Settings
spring.h2.console.enabled=true

# (Optional) Customize the path, default is /h2-console
spring.h2.console.path=/h2-console

# 2. Database Connection (JDBC) Settings
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=always 


#1. DEFAULT LOGGING  LEVELS----
# Global fallback level (Defaults to INFO if not set)
logging.level.root=INFO

# Turn on detailed logging for your own application code
logging.level.com.example.demo=DEBUG

# Silence noisy framework logs by raising their threshold
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=DEBUG

#2. CONFIGURE OUTPUT FILES---
# Option A: Specify a relative or absolute file name
logging.file.name=logs/application.log

# Option B: Or specify just a directory (Spring creates a file named 'spring.log' inside it)
# logging.file.path=/var/log/myapp

# OPTIONAL: Tweak the file rotation behavior ---- (FOR ACTUATOR)
#logging.logback.rollingpolicy.max-file-size=20MB
#logging.logback.rollingpolicy.max-history=15

#3. CUSTOMIZE CONSOLE AND FILE FORMATS
# Custom format for the terminal window
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  - %msg%n
#
## Separate custom format for the log file (e.g., omitting ANSI colors)
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n


